### PR TITLE
'works' section

### PR DESCRIPTION
**Pull request by MattGomb**
In this pull request I attempt to create the rest of the mobile-template:

- added 4+1 grid elements, 1column, 5 rows.
- created a unified display for all elements
- positioned parts of elements with flexbox

### CODE REVIEW

**Comment by MattGomb** [comment]
✖  Unexpected missing generic font family   font-family-no-missing-generic-family-keyword - I tried to research this problem for a couple of hours, nothing worked.

**Review by aimemalaika — APPROVED** [review]
Hi @MattGomb, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aimemalaika** [comment]
Hello @MattGomb,

Kindly work on the linters errors in your CSS.

Sorry for approving without checking that. Kindly fix that then resubmit the PR for review.

Thank for understunding

**Review by awais-amjed — APPROVED** [review]
# STATUS: APPROVED 🥳

Hi @MattGomb , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on implementing the required changes! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No Linter issues ✔️ 
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

gif

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
